import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs"; // 👈 1. IMPORTAR ESTO

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="es">
      {/* CAMBIOS REALIZADOS:
         1. Agregué las variables de fuente al className.
         2. Agregué 'antialiased' para suavizado de texto.
      */}
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        <Navbar />
        
        <main className="container mx-auto p-4">
          {children}
        </main>
        
      </body>
    </html>
    </ClerkProvider>
  );
}
